[package]
name = "find_root"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14"
num-traits = "0.2.14"

[dev-dependencies]
approx = "0.5.0"
